name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag argus:latest
      
    - name: Check repo 
      run: docker run argus:latest --mode repo --url https://github.com/SonarSource/sonarqube-scan-action
